-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  currency_code character DEFAULT 'USD'::bpchar CHECK (length(currency_code) = 3),
  timezone text DEFAULT 'UTC'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  logo_url text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'rejected'::text])),
  country character varying,
  slug text,
  address text,
  billing_data jsonb,
  default_receipt_format text CHECK (default_receipt_format = ANY (ARRAY['thermal'::text, 'half_letter'::text])),
  lodging_checkout_deadline time without time zone DEFAULT '12:00:00'::time without time zone,
  lodging_stay_cutoff_time time without time zone DEFAULT '12:00:00'::time without time zone,
  lodging_late_checkout_penalty numeric DEFAULT 0 CHECK (lodging_late_checkout_penalty >= 0::numeric),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  price_monthly numeric NOT NULL,
  price_yearly numeric NOT NULL,
  max_branches integer NOT NULL DEFAULT 1,
  max_users integer NOT NULL DEFAULT 5,
  max_storage_mb integer DEFAULT 1000,
  feature_multi_branch boolean DEFAULT false,
  feature_manager_role boolean DEFAULT false,
  feature_inventory_transfer boolean DEFAULT false,
  feature_api_access boolean DEFAULT false,
  feature_white_label boolean DEFAULT false,
  feature_advanced_reports boolean DEFAULT false,
  feature_forensic_export boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  business_only boolean NOT NULL DEFAULT false,
  description text NOT NULL DEFAULT ''::text,
  resume text NOT NULL DEFAULT ''::text,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  limits jsonb NOT NULL DEFAULT '{}'::jsonb,
  available_billing_modes jsonb NOT NULL DEFAULT '{}'::jsonb,
  trial boolean NOT NULL DEFAULT false,
  trial_duration integer,
  feature_hotel_module boolean DEFAULT false,
  allowed_business_types ARRAY DEFAULT '{product,service,lodging}'::business_type_enum[],
  max_business_types integer DEFAULT 1,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organization_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL UNIQUE,
  plan_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'trial'::sub_status,
  current_period_start timestamp with time zone DEFAULT now(),
  current_period_end timestamp with time zone NOT NULL,
  provider_subscription_id text,
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  billing_mode text DEFAULT 'monthly'::text CHECK (billing_mode = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'annual'::text])),
  payment_method text CHECK (payment_method IS NULL OR (payment_method = ANY (ARRAY['tarjeta'::text, 'efectivo'::text, 'transferencia'::text, 'qr'::text]))),
  trial_ends_at timestamp with time zone,
  is_trial boolean NOT NULL DEFAULT false,
  invoice_name text,
  doc_type text CHECK (doc_type = ANY (ARRAY['nit'::text, 'ci'::text, 'pasaporte'::text, 'cedula'::text])),
  doc_number text,
  CONSTRAINT organization_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT organization_subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  code text NOT NULL,
  address text,
  phone text,
  is_active boolean DEFAULT true,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  organization_id uuid,
  full_name text NOT NULL,
  email text NOT NULL,
  role USER-DEFINED DEFAULT 'client'::user_role,
  avatar_url text,
  phone text,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  trial_consumed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role_id uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT profiles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.user_roles(id)
);
CREATE TABLE public.employee_branch_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  can_manage_inventory boolean DEFAULT false,
  can_override_prices boolean DEFAULT false,
  skills jsonb DEFAULT '[]'::jsonb,
  is_primary boolean DEFAULT false,
  CONSTRAINT employee_branch_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT employee_branch_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT employee_branch_assignments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['product'::text, 'service'::text, 'lodging'::text])),
  parent_id uuid,
  is_active boolean DEFAULT true,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  category_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_url text,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT services_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  sku text,
  name text NOT NULL,
  description text,
  cost_price numeric DEFAULT 0 CHECK (cost_price >= 0::numeric),
  sale_price numeric NOT NULL CHECK (sale_price >= 0::numeric),
  category_id uuid,
  track_inventory boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_url text,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.inventory_stock (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  branch_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer DEFAULT 0 CHECK (quantity >= 0),
  min_stock_level integer DEFAULT 5 CHECK (min_stock_level >= 0),
  reserved_quantity integer DEFAULT 0 CHECK (reserved_quantity >= 0),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_stock_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_stock_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  customer_id uuid,
  customer_name text,
  customer_phone text,
  employee_id uuid NOT NULL,
  service_id uuid NOT NULL,
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::appointment_status,
  notes text,
  cancelled_by uuid,
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  transaction_id uuid,
  source USER-DEFINED NOT NULL DEFAULT 'manual'::appointment_source,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id),
  CONSTRAINT appointments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT appointments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT appointments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id),
  CONSTRAINT appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT appointments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.clients(id),
  CONSTRAINT appointments_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  invoice_number integer NOT NULL DEFAULT nextval('transactions_invoice_number_seq'::regclass),
  customer_id uuid,
  employee_id uuid NOT NULL,
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  tax_amount numeric DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  final_amount numeric NOT NULL CHECK (final_amount >= 0::numeric),
  payment_method USER-DEFINED DEFAULT 'cash'::payment_method,
  type USER-DEFINED DEFAULT 'sale'::transaction_type,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['completed'::text, 'refunded'::text, 'voided'::text])),
  refund_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT transactions_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT transactions_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id),
  CONSTRAINT transactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.clients(id)
);
CREATE TABLE public.transaction_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id uuid NOT NULL,
  product_id uuid,
  service_id uuid,
  quantity integer NOT NULL CHECK (quantity <> 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  item_type text NOT NULL CHECK (item_type = ANY (ARRAY['product'::text, 'service'::text])),
  snapshot_data jsonb,
  appointment_id uuid,
  CONSTRAINT transaction_items_pkey PRIMARY KEY (id),
  CONSTRAINT transaction_items_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id),
  CONSTRAINT transaction_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT transaction_items_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT transaction_items_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.audit_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  logged_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  action USER-DEFINED NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  old_data jsonb,
  new_data jsonb,
  ip_address inet,
  user_agent text,
  context jsonb,
  checksum text,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  product_id uuid NOT NULL,
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['entry'::text, 'exit'::text, 'adjustment'::text, 'transfer_in'::text, 'transfer_out'::text])),
  quantity integer NOT NULL CHECK (quantity > 0),
  previous_quantity integer NOT NULL CHECK (previous_quantity >= 0),
  new_quantity integer NOT NULL CHECK (new_quantity >= 0),
  reason text,
  note text,
  reference_type text,
  reference_id uuid,
  source_branch_id uuid,
  destination_branch_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  reference_code text,
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_movements_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_movements_source_branch_id_fkey FOREIGN KEY (source_branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_movements_destination_branch_id_fkey FOREIGN KEY (destination_branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.onboarding_progress (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  organization_id uuid,
  current_step text CHECK (current_step = ANY (ARRAY['registration'::text, 'verification'::text, 'organization'::text, 'payment'::text, 'completed'::text])),
  progress_data jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT onboarding_progress_pkey PRIMARY KEY (id),
  CONSTRAINT onboarding_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT onboarding_progress_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payment_validations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_method text DEFAULT 'bank_transfer'::text,
  transaction_ref text,
  receipt_storage_path text NOT NULL,
  receipt_filename text NOT NULL,
  receipt_mime_type text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  rejection_reason text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reviewed_by_system_user uuid,
  CONSTRAINT payment_validations_pkey PRIMARY KEY (id),
  CONSTRAINT payment_validations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT payment_validations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT payment_validations_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT payment_validations_reviewed_by_system_user_fkey FOREIGN KEY (reviewed_by_system_user) REFERENCES auth.users(id)
);
CREATE TABLE public.system_users (
  user_id uuid NOT NULL,
  full_name text,
  email text,
  role text NOT NULL DEFAULT 'system'::text CHECK (role = 'system'::text),
  is_active boolean NOT NULL DEFAULT true,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT system_users_pkey PRIMARY KEY (user_id),
  CONSTRAINT system_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT system_users_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.guest_customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  branch_id uuid,
  full_name text NOT NULL,
  phone text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  notification_preferences jsonb DEFAULT '{"whatsapp": true}'::jsonb,
  CONSTRAINT guest_customers_pkey PRIMARY KEY (id),
  CONSTRAINT guest_customers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT guest_customers_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT guest_customers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  first_name text NOT NULL,
  last_name text,
  phone text,
  email text,
  billing_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  notification_preferences jsonb DEFAULT '{"email": true, "whatsapp": true}'::jsonb,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.client_org (
  client_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'blocked'::text])),
  billing_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  document_type text DEFAULT 'SIN_DOC'::text CHECK (document_type = ANY (ARRAY['NIT'::text, 'CI'::text, 'SIN_DOC'::text])),
  document_number text,
  billing_name text,
  billing_email text,
  billing_phone text,
  is_anonymous_template boolean NOT NULL DEFAULT false,
  CONSTRAINT client_org_pkey PRIMARY KEY (client_id, organization_id),
  CONSTRAINT client_org_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT client_org_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code USER-DEFINED NOT NULL UNIQUE,
  name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  is_system boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.role_module_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  role_id uuid NOT NULL,
  module_key text NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_create boolean NOT NULL DEFAULT false,
  can_edit boolean NOT NULL DEFAULT false,
  can_delete boolean NOT NULL DEFAULT false,
  can_export boolean NOT NULL DEFAULT false,
  can_manage boolean NOT NULL DEFAULT false,
  can_approve boolean NOT NULL DEFAULT false,
  can_assign boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT role_module_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_module_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.user_roles(id)
);
CREATE TABLE public.system_role_module_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  system_role text NOT NULL CHECK (system_role = ANY (ARRAY['system'::text, 'support'::text])),
  module_key text NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_create boolean NOT NULL DEFAULT false,
  can_edit boolean NOT NULL DEFAULT false,
  can_delete boolean NOT NULL DEFAULT false,
  can_export boolean NOT NULL DEFAULT false,
  can_manage boolean NOT NULL DEFAULT false,
  can_approve boolean NOT NULL DEFAULT false,
  can_assign boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_role_module_permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transfers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  source_branch_id uuid NOT NULL,
  destination_branch_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'cancelled'::text])),
  observations text,
  requested_by uuid NOT NULL,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  received_by uuid,
  received_at timestamp with time zone,
  cancelled_by uuid,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reference_code text,
  CONSTRAINT inventory_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transfers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_transfers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_transfers_source_branch_id_fkey FOREIGN KEY (source_branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_transfers_destination_branch_id_fkey FOREIGN KEY (destination_branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_transfers_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT inventory_transfers_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id),
  CONSTRAINT inventory_transfers_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory_adjust_batches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['set'::text, 'add'::text, 'remove'::text])),
  reason text NOT NULL,
  note text,
  total_lines integer NOT NULL CHECK (total_lines > 0),
  processed_count integer NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
  processed_by uuid,
  idempotency_key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_adjust_batches_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_adjust_batches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_adjust_batches_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_adjust_batches_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory_transfer_batches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  source_branch_id uuid NOT NULL,
  destination_branch_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'cancelled'::text])),
  observations text,
  total_lines integer NOT NULL CHECK (total_lines > 0),
  total_quantity integer NOT NULL CHECK (total_quantity > 0),
  requested_by uuid,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  received_by uuid,
  received_at timestamp with time zone,
  idempotency_key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reference_code text,
  CONSTRAINT inventory_transfer_batches_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transfer_batches_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_transfer_batches_source_branch_id_fkey FOREIGN KEY (source_branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_transfer_batches_destination_branch_id_fkey FOREIGN KEY (destination_branch_id) REFERENCES public.branches(id),
  CONSTRAINT inventory_transfer_batches_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT inventory_transfer_batches_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory_transfer_batch_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  batch_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'received'::text, 'cancelled'::text])),
  source_previous_quantity integer,
  source_new_quantity integer,
  destination_previous_quantity integer,
  destination_new_quantity integer,
  received_by uuid,
  received_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_transfer_batch_lines_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transfer_batch_lines_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.inventory_transfer_batches(id),
  CONSTRAINT inventory_transfer_batch_lines_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT inventory_transfer_batch_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_transfer_batch_lines_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory_document_sequences (
  organization_id uuid NOT NULL,
  doc_type text NOT NULL CHECK (doc_type = ANY (ARRAY['ING'::text, 'SAL'::text, 'AJU'::text, 'TRA'::text])),
  seq_year integer NOT NULL CHECK (seq_year >= 2000),
  last_value integer NOT NULL DEFAULT 0 CHECK (last_value >= 0),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inventory_document_sequences_pkey PRIMARY KEY (organization_id, doc_type, seq_year),
  CONSTRAINT inventory_document_sequences_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.client_org_billing_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  document_type text NOT NULL CHECK (document_type = ANY (ARRAY['NIT'::text, 'CI'::text, 'SIN_DOC'::text])),
  document_number text,
  billing_name text,
  billing_email text,
  billing_phone text,
  is_active_version boolean NOT NULL DEFAULT true,
  change_reason text,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT client_org_billing_history_pkey PRIMARY KEY (id),
  CONSTRAINT client_org_billing_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles(id),
  CONSTRAINT client_org_billing_history_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT client_org_billing_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.profile_client_map (
  profile_id uuid NOT NULL,
  client_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profile_client_map_pkey PRIMARY KEY (profile_id),
  CONSTRAINT profile_client_map_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT profile_client_map_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.billing_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  plan_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['plan_change'::text, 'payment'::text, 'cancellation'::text, 'reactivation'::text, 'trial_start'::text, 'trial_end'::text, 'proration_credit'::text, 'proration_charge'::text])),
  amount numeric,
  currency text DEFAULT 'USD'::text,
  billing_mode text CHECK (billing_mode = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'annual'::text])),
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT billing_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT billing_ledger_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT billing_ledger_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT billing_ledger_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organization_siat_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  razon_social text,
  nit text,
  regimen_tributario text CHECK (regimen_tributario = ANY (ARRAY['general'::text, 'simplificado'::text, 'especial'::text])),
  actividad_economica text,
  sucursal_siat text,
  direccion_matriz text,
  codigo_autorizacion text,
  punto_venta text,
  sistema_facturacion text CHECK (sistema_facturacion = ANY (ARRAY['propio'::text, 'terceros'::text, 'siat_linea'::text])),
  codigo_sistema text,
  resolucion_numero text,
  is_active boolean DEFAULT false,
  last_sync_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_siat_config_pkey PRIMARY KEY (id),
  CONSTRAINT organization_siat_config_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['sale_receipt'::text, 'appointment_confirmation'::text, 'appointment_reminder'::text, 'appointment_status_change'::text])),
  whatsapp_template_name text NOT NULL,
  template_body text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL UNIQUE,
  whatsapp_enabled boolean DEFAULT false,
  whatsapp_phone_id text,
  whatsapp_access_token text,
  whatsapp_business_account_id text,
  send_sale_receipt boolean DEFAULT true,
  send_appointment_confirmation boolean DEFAULT true,
  send_appointment_reminder boolean DEFAULT true,
  send_appointment_status_change boolean DEFAULT true,
  reminder_minutes_before integer DEFAULT 60,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  notification_type text NOT NULL,
  channel text NOT NULL DEFAULT 'whatsapp'::text,
  recipient_phone text NOT NULL,
  recipient_name text,
  template_id uuid,
  payload jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'delivered'::text, 'read'::text])),
  whatsapp_message_id text,
  error_message text,
  retry_count integer DEFAULT 0,
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notifications_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id)
);
CREATE TABLE public.room_types (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  base_price numeric NOT NULL CHECK (base_price >= 0::numeric),
  max_guests integer NOT NULL CHECK (max_guests > 0),
  amenities jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT room_types_pkey PRIMARY KEY (id),
  CONSTRAINT room_types_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.rooms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  room_number text NOT NULL,
  floor integer,
  status USER-DEFINED DEFAULT 'available'::room_status,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category_id uuid NOT NULL,
  base_price numeric NOT NULL DEFAULT 0,
  CONSTRAINT rooms_pkey PRIMARY KEY (id),
  CONSTRAINT rooms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT rooms_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT rooms_category_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  check_in date NOT NULL,
  check_out date NOT NULL,
  nights integer DEFAULT (check_out - check_in),
  status USER-DEFINED DEFAULT 'pending'::reservation_status,
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  paid_amount numeric DEFAULT 0 CHECK (paid_amount >= 0::numeric),
  source text DEFAULT 'staff'::text CHECK (source = 'staff'::text),
  notes text,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  actual_check_in_at timestamp with time zone,
  actual_check_out_at timestamp with time zone,
  is_open_ended boolean NOT NULL DEFAULT false,
  extended_from_check_out date,
  extension_notes text,
  CONSTRAINT reservations_pkey PRIMARY KEY (id),
  CONSTRAINT reservations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT reservations_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT reservations_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id),
  CONSTRAINT reservations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.reservation_rooms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reservation_id uuid NOT NULL,
  room_id uuid NOT NULL,
  room_price numeric NOT NULL CHECK (room_price >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_rooms_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id),
  CONSTRAINT reservation_rooms_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.rooms(id)
);
CREATE TABLE public.reservation_guests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reservation_room_id uuid NOT NULL,
  full_name text NOT NULL,
  document_type text,
  document_number text,
  address text,
  phone text,
  email text,
  nationality text,
  is_main_guest boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  birth_date date,
  sex text CHECK (sex IS NULL OR (sex = ANY (ARRAY['male'::text, 'female'::text, 'other'::text]))),
  marital_status text,
  CONSTRAINT reservation_guests_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_guests_reservation_room_id_fkey FOREIGN KEY (reservation_room_id) REFERENCES public.reservation_rooms(id)
);
CREATE TABLE public.reservation_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  reservation_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['cash'::text, 'card'::text, 'transfer'::text, 'qr'::text, 'digital_wallet'::text])),
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['deposit'::text, 'balance'::text, 'full'::text])),
  reference text,
  notes text,
  paid_at timestamp with time zone DEFAULT now(),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reservation_payments_pkey PRIMARY KEY (id),
  CONSTRAINT reservation_payments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT reservation_payments_reservation_id_fkey FOREIGN KEY (reservation_id) REFERENCES public.reservations(id),
  CONSTRAINT reservation_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pos_number_sequences (
  organization_id uuid NOT NULL,
  sales_order_last bigint NOT NULL DEFAULT 0,
  proforma_last bigint NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pos_number_sequences_pkey PRIMARY KEY (organization_id),
  CONSTRAINT pos_number_sequences_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.sales_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  sales_order_number bigint NOT NULL,
  created_by uuid NOT NULL,
  customer_mode text NOT NULL CHECK (customer_mode = ANY (ARRAY['existing'::text, 'walk_in'::text])),
  customer_id uuid,
  customer_full_name text NOT NULL,
  customer_phone text,
  customer_email text,
  discount_type text NOT NULL DEFAULT 'none'::text CHECK (discount_type = ANY (ARRAY['none'::text, 'percentage'::text, 'fixed'::text])),
  discount_value numeric NOT NULL DEFAULT 0 CHECK (discount_value >= 0::numeric),
  subtotal numeric NOT NULL DEFAULT 0 CHECK (subtotal >= 0::numeric),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  final_amount numeric NOT NULL DEFAULT 0 CHECK (final_amount >= 0::numeric),
  note text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'ready_to_charge'::text, 'charged'::text, 'cancelled'::text])),
  charged_transaction_id uuid,
  charged_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_orders_pkey PRIMARY KEY (id),
  CONSTRAINT sales_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT sales_orders_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT sales_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.clients(id),
  CONSTRAINT sales_orders_charged_transaction_id_fkey FOREIGN KEY (charged_transaction_id) REFERENCES public.transactions(id)
);
CREATE TABLE public.sales_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sales_order_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  item_type text NOT NULL CHECK (item_type = ANY (ARRAY['product'::text, 'service'::text])),
  product_id uuid,
  service_id uuid,
  employee_id uuid,
  scheduled_date text,
  scheduled_time text,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  snapshot_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT sales_order_items_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT sales_order_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT sales_order_items_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT sales_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT sales_order_items_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT sales_order_items_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.sales_proformas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  sales_order_id uuid NOT NULL,
  proforma_number bigint NOT NULL,
  status text NOT NULL DEFAULT 'issued'::text CHECK (status = ANY (ARRAY['issued'::text, 'cancelled'::text, 'consumed'::text])),
  snapshot jsonb NOT NULL,
  issued_by uuid NOT NULL,
  issued_at timestamp with time zone NOT NULL DEFAULT now(),
  consumed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sales_proformas_pkey PRIMARY KEY (id),
  CONSTRAINT sales_proformas_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT sales_proformas_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT sales_proformas_sales_order_id_fkey FOREIGN KEY (sales_order_id) REFERENCES public.sales_orders(id),
  CONSTRAINT sales_proformas_issued_by_fkey FOREIGN KEY (issued_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_business_types (
  organization_id uuid NOT NULL,
  business_type USER-DEFINED NOT NULL,
  CONSTRAINT organization_business_types_pkey PRIMARY KEY (organization_id, business_type),
  CONSTRAINT organization_business_types_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_storefront_settings (
  organization_id uuid NOT NULL,
  business_type USER-DEFINED NOT NULL DEFAULT 'product'::business_type_enum,
  template_key text NOT NULL,
  color_preset_key text NOT NULL DEFAULT 'neutral'::text,
  primary_color text NOT NULL DEFAULT '#111827'::text CHECK (primary_color ~ '^#[0-9A-Fa-f]{6}$'::text),
  secondary_color text NOT NULL DEFAULT '#F3F4F6'::text CHECK (secondary_color ~ '^#[0-9A-Fa-f]{6}$'::text),
  accent_color text NOT NULL DEFAULT '#2563EB'::text CHECK (accent_color ~ '^#[0-9A-Fa-f]{6}$'::text),
  company_description text,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  hero_image_url text,
  CONSTRAINT organization_storefront_settings_pkey PRIMARY KEY (organization_id),
  CONSTRAINT organization_storefront_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.organization_storefront_entitlements (
  organization_id uuid NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_manage boolean NOT NULL DEFAULT false,
  can_publish boolean NOT NULL DEFAULT false,
  can_custom_colors boolean NOT NULL DEFAULT false,
  max_sites integer NOT NULL DEFAULT 0 CHECK (max_sites >= 0),
  template_keys ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_storefront_entitlements_pkey PRIMARY KEY (organization_id),
  CONSTRAINT organization_storefront_entitlements_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
